import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div lang="en">
      <Head>
        <title>EXAMPLE APP</title>
        <meta name="description" content="Example" />
      </Head>
      <main className={inter.className}>{children}</main>
    </div>
  );
}
